Merged in Peters changes.

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -5,6 +5,7 @@ INCLUDES = @INCLTDL@ -I$(srcdir)/plat/linux32
 bin_PROGRAMS =  yacas
 noinst_PROGRAMS = mkfastprimes check_plugins plugin_stub_gen testnum gencorefunctions @COMPRESSOR_PRG@
 EXTRA_PROGRAMS = compressor
+libmath_USES = yacas$(EXEEXT) check_plugins$(EXEEXT)
 
 lib_LTLIBRARIES = libyacas.la libyacasplatform.la libcyacas.la @NUMBERS_LIB@ 
 EXTRA_LTLIBRARIES = libgmpnumbers.la libyacasnumbers.la 
@@ -77,15 +78,33 @@ libyacasnumbers_la_LDFLAGS = -rpath $(libdir)
 libgmpnumbers_la_SOURCES = gmpnumbers.cpp numbers.cpp
 libgmpnumbers_la_LDFLAGS = -rpath $(libdir)
 
-# The libmath.cpp source file is generated as follows
+# We need iteration (rebuilding the same target multiple times).
+# This variable ensures non-empty cmd-goals, taking automake's default, "all".
+# Thus, we can redo the original request, with additions.
+#ITERATIVEMAKE = $(MAKE) $(MAKEFLAGS) $(MAKECMDGOALS) `test -n "$(MAKECMDGOALS)" || all`
+# Belay that order, Mr. Sulu!  What if the request was "make clean test"?  Use the innocuous "check" for now.
+ITERATIVEMAKE = $(MAKE) $(MAKEFLAGS) check
 
-$(srcdir)/libmath.cpp: $(top_srcdir)/scripts/base.rep/math.ys yacas$(EXEEXT) check_plugins
-	(cd ../scripts && make packages.ys corefunctions.ys)
+# The libmath.cpp source file is generated as follows
+# TODO: Get the dependency (on .ys components) right, not piecemeal
+
+$(srcdir)/libmath.cpp: \
+		$(top_srcdir)/scripts/base.rep/math.ys \
+		$(top_srcdir)/scripts/compile.rep/compilecpp.ys
+	(cd ../scripts && $(MAKE) packages.ys corefunctions.ys)
 	echo "Set(LoadPlugIns,False);Use(\"yacasinit.ys\");" > compileinit.txt
 	echo "CompileCpp(\"base.rep/math.ys\",\"libmath\");" > compile.txt
-	./yacas$(EXEEXT) --rootdir  $(top_srcdir)/scripts -pc --init compileinit.txt compile.txt
-	./check_plugins
-	make
+	@need='' list='$(libmath_USES)'; for p in $$list; do \
+	  if test ! -f $$p; then need="$$need $$p"; fi; \
+	done; \
+    test -z "$$need" || $(MAKE) $(MAKEFLAGS) $$need
+	-@ echo "Bad if crash or abort between next two commands."
+	./yacas --rootdir $(top_srcdir)/scripts -pc --init compileinit.txt compile.txt
+	./check_plugins || $(ITERATIVEMAKE) $(libmath_USES)
+
+$(srcdir)/plugins_available.h:
+	test -f check_plugins$(EXEEXT) || $(MAKE) $(MAKEFLAGS) check_plugins$(EXEEXT)
+	./check_plugins || echo "More to do..."
 
 # We used to have "libmath_la_LIBADD = libmath.lo" because libmath.cpp
 # is a built source. However, this broke the build process on some
@@ -146,7 +165,7 @@ EXTRA_DIST = anumber.inl deffile.inl epocfileio.cpp epocmain.cpp epocmaincmd.cpp
 	README.LZO lzoconf.h minilzo.c minilzo.h decompressor.cpp \
 	compressor.cpp filescanner.cpp filescanner.h \
 	compressedfiles.h compress.bat \
-	compressor.dsp compressor.dsw win32rcwriter.cpp yacas.pas biginteger.cpp \
+	compressor.dsp compressor.dsw win32rcwriter.cpp yacas.pas biginteger.cpp libmath.cpp \
   libmath_stub.cpp pcre_study_stub.c pcre_pcre_stub.c pcre_maketables_stub.c \
   pcre_pcreposix_stub.c pcre_get_stub.c pcre_plugin_stub.cpp \
   filescanner_stub.cpp filescanner_plugin_stub.cpp \
@@ -162,13 +181,6 @@ fastprimes.c: mkfastprimes
 	./mkfastprimes > fastprimes.c
 # We don't want $(srcdir)/mkfastprimes because this executable
 # is not generated inside the $(srcdir). 
-
-
-dummy:
-
-$(srcdir)/plugins_available.h: check_plugins dummy
-	./check_plugins
-
 
 libmath_stub.cpp:plugin_stub_gen $(srcdir)/plugins_available.h 
 	./plugin_stub_gen libmath_stub.cpp libmath.cpp
@@ -200,10 +212,9 @@ filescanner_plugin_stub.cpp:plugin_stub_gen $(srcdir)/plugins_available.h
 
 #workaround that hopefully allows compiling Yacas out of the box, 
 #dependency on the plugins_available.h header file
+exedll.$(OBJEXT) yacasmain.$(OBJEXT): $(srcdir)/plugins_available.h
 
-exedll.cpp: $(srcdir)/plugins_available.h
-
-yacasmain.cpp: $(srcdir)/plugins_available.h
+exedll.cpp yacasmain.cpp: $(srcdir)/plugins_available.h
 
 
 yacas_include = $(datadir)/yacas/include
diff --git a/tests/test-yacas b/tests/test-yacas
--- a/tests/test-yacas
+++ b/tests/test-yacas
@@ -1,79 +1,140 @@
 #! /bin/sh
 #
-# Script for testing Yacas
+# test-yacas -- Script for testing Yacas
 
 # Give help, if requested
 
 if [ $# -eq 0 ] || [ "x$1" = "x-h" ] || [ "x$1" = "x--help" ]; then
-    echo "Usage: test-yacas <cmd> ; <dir> <scripts>"
-    echo "  cmd      Command plus options, needed to run Yacas"
-    echo "  dir      Directory in which scripts reside"
-    echo "  scripts  List of test scripts to be run"
+    echo "Usage: $0 <cmd> <dir> <script>..."
+    echo "  cmd       Command plus options, needed to run Yacas"
+    echo "  dir       Directory in which scripts reside"
+    echo "  script... Test scripts to be run"
     echo "Test script may reside in <dir> or in the current directory"
     echo "Exit status is number of tests scripts which fail"
+    echo "Example:"
+    echo "  $0 \"../src/Debug/yacas --archive ../src/scripts.dat\" . short*.yts"
     exit 0
 fi
 
 # Parse arguments
 
-CMD=""
-while [ $# -ge 1 ] && [ "x$1" != "x;" ]; do
-    CMD="$CMD $1"
-    shift
-done
-if [ $# -eq 0 ]; then
-    echo "Error: could not find semi-colon terminating the command"
+if [ $# -lt 2 ]; then
+    echo "Error: $0: Missing parameters"
     exit 255
 fi
-shift # gobble semi-colon
 
-if [ $# -eq 0 ]; then
-    echo "Error: no arguments after semi-colon"
-    exit 255
-fi
-SCRIPTDIR=$1
+CMD="$1"
+SCRIPTDIR="$2"
+shift
 shift
 SCRIPTS=$*
 
 # run the tests
 
-FAILED_TESTS=""  # containes list of failed tests
-FAILURES=0       # number of fails tests
-NOF_TESTS=0      # total number of tests
-TMPFILE=/tmp/test-yacas.$$
+FAILED_TESTS=""  # list of failed tests
+FAILURES=0       # number of failed tests
+TOTALTESTS=0     # total number of tests
+
+TESTFILE=/tmp/test-yacas.$$
+TIMEFILE=/tmp/time-yacas.$$
+VERSIONF=/tmp/version-yacas-$$.ys
+LOGFILE=yacas-logfile.txt
+echo "Print(Version());" > $VERSIONF
+VERSION=`$CMD -c $VERSIONF`
+echo "Print(CodeComment());" > $VERSIONF
+COMMENT=`$CMD -c $VERSIONF`
+#DATECMD="date \"+%F %T\""
+#echo "$DATECMD"
+rm $VERSIONF
+
+echo "/*" >> $LOGFILE
+echo "Command = \"$CMD\""      | tee -a $LOGFILE
+echo "Version = $VERSION"      | tee -a $LOGFILE
+echo "Comment = $COMMENT"      | tee -a $LOGFILE
+echo "Date = \"`date "+%F %T"`\""   | tee -a $LOGFILE
+echo "Logfile = \"$LOGFILE\""  | tee -a $LOGFILE
+echo "*/" >> $LOGFILE
+
+REALTOT="0"
+USERTOT="0"
+SYSSTOT="0"
 
 for scr in $SCRIPTS; do
     if [ -f $SCRIPTDIR/$scr ]; then
-	f=$SCRIPTDIR/$scr
-    else 
-	f=$scr
+	   f=$SCRIPTDIR/$scr
+    else
+	   f=$scr
     fi
+#		if grep -i "interrupt" $TESTFILE > /dev/null; then
+#			PASSFAIL=Interrupted
+#		fi
     echo "Running $scr"
-    ($CMD $f || echo "Error: exit status $?") | tee $TMPFILE
-    if grep -E "\*\*\*\*\*\*|Error" $TMPFILE > /dev/null; then
+	if [ -f $TESTFILE ]; then rm $TESTFILE ; fi
+    /bin/sh -c "time -p ($CMD $f || echo \"Error: exit status $?\") | tee $TESTFILE" \
+		2> $TIMEFILE \
+		|| (echo "Error -- User interrupt" > $TESTFILE)
+#	cat $TIMEFILE
+    if grep -E "\*\*\*\*\*\*|Error|interrupt" $TESTFILE > /dev/null; then
+        PASSFAIL=Fail
         FAILED_TESTS="$FAILED_TESTS $scr"
         FAILURES=`expr $FAILURES + 1`
+		if grep -i "interrupt" $TESTFILE > /dev/null; then
+			PASSFAIL=Interrupted
+		fi
+    else
+        PASSFAIL=Pass
     fi
-    NOF_TESTS=`expr $NOF_TESTS + 1`
+    TOTALTESTS=`expr $TOTALTESTS + 1`
+
+    REAL=`grep real $TIMEFILE | sed 's/real//'`
+    USER=`grep user $TIMEFILE | sed 's/user//'`
+    SYSS=`grep sys  $TIMEFILE | sed 's/sys//'`
+    LOGLINE="{\"$scr\", $VERSION, \"`date "+%F %T"`\", $REAL, $USER, $SYSS, $PASSFAIL},"
+    echo "$LOGLINE" | tee -a $LOGFILE
+
+	REALTOT="$REALTOT+$REAL"
+	USERTOT="$USERTOT+$USER"
+	SYSSTOT="$SYSSTOT+$SYSS"
+### exit
+
 done
 
-rm $TMPFILE
+if [ $FAILURES -eq 0 ]; then
+    PASSFAIL=Pass
+else
+    PASSFAIL=Fail
+fi
+REAL=`$CMD -i "Print($REALTOT);"`
+USER=`$CMD -i "Print($USERTOT);"`
+SYSS=`$CMD -i "Print($SYSSTOT);"`
+LOGLINE="{\"Total\", $VERSION, \"`date "+%F %T"`\", $REAL, $USER, $SYSS, $PASSFAIL},"
+echo "$LOGLINE" | tee -a $LOGFILE
+
+rm $TESTFILE $TIMEFILE
 
 # report
 
 if [ $FAILURES -eq 0 ]; then
-    RES="All $NOF_TESTS tests PASSED"
+    RES="All $TOTALTESTS tests PASSED"
 else
     if [ $FAILURES -eq 1 ]; then
         echo "Failed test: $FAILED_TESTS"
     else
         echo "Failed tests: $FAILED_TESTS"
-    fi   
-    RES="$FAILURES of $NOF_TESTS tests FAILED"
+    fi
+    RES="$FAILURES of $TOTALTESTS tests FAILED"
 fi
 EQS=`echo $RES | sed 's/./=/g'`
-echo $EQS
-echo $RES
-echo $EQS
+
+echo "Command = \"$CMD\""
+echo "Version = $VERSION"
+echo "Date = \"`date "+%F %T"`\""
+echo "Logfile = \"$LOGFILE\""
+echo "/*$EQS" | tee -a $LOGFILE
+if [ "x$FAILED_TESTS" != "x" ]; then
+    echo "Failed = $FAILED_TESTS" | tee -a $LOGFILE
+fi
+echo " $RES " | tee -a $LOGFILE
+echo "$EQS*/" | tee -a $LOGFILE
 
 exit $FAILURES
